### PR TITLE
delay calling distmeta until filemunging phase

### PR DESCRIPTION
**Pull request by karenetheridge**
In one distribution I was constructing, I needed to remove this plugin because it was forcing all plugins' MetaProvider phase to fire prematurely, before all files had even been added to the dist.  Delaying munging the template content until the filemunging phase fixes this -- the filegathering phase should just add static content.

### CODE REVIEW

**Comment by xenoterracide** [comment]
alright, could you fix the failing tests?

**Comment by karenetheridge** [comment]
They passed on my box (with `@TestingMania` disabled, as it won't build on darwin 5.19.8) -- checking travis.

**Comment by karenetheridge** [comment]
pod coverage and critic tests should now pass.

**Comment by xenoterracide** [comment]
yeah I'm slowly removing TestingMania due to specific things it pulls in that always cause problems. I'll probably go ahead and remove it here for that reason.

**Comment by xenoterracide** [comment]
```
 ===(      53;1  0/?  0/?  0/? )=========================================Variable "$set_spell_cmd" is not imported at t/author-pod-spell.t line 17.
    (Did you mean &set_spell_cmd instead?)
Variable "$add_stopwords" is not imported at t/author-pod-spell.t line 18.
    (Did you mean &add_stopwords instead?)
 syntax error at t/author-pod-spell.t line 15, near "use {"
Global symbol "$wordlist" requires explicit package name at t/author-pod-spell.t line 15.
Global symbol "$set_spell_cmd" requires explicit package name at t/author-pod-spell.t line 17.
Global symbol "$add_stopwords" requires explicit package name at t/author-pod-spell.t line 18.
Global symbol "$stopwords" requires explicit package name at t/author-pod-spell.t line 20.
Execution of t/author-pod-spell.t aborted due to compilation errors.
t/author-pod-spell.t .......... Dubious, test returned 255 (wstat 65280, 0xff00)
```

bisect shows this was caused by this patch. I need to get this fixed, and a test added that would catch this regression. I thought my test suite did have tests to catch this, maybe something about the stage change... but I thought `Bootstrap::lib` would make the generated test the same as the final test. I'm looking into it, but if I can't find a fix in a couple of hours I have to revert this to avoid breaking someone elses code.

**Comment by karenetheridge** [comment]
On Sun, Feb 23, 2014 at 10:53:48AM -0800, Caleb Cushing wrote:

> ===(      53;1  0/?  0/?  0/? )=========================================Variable "$set_spell_cmd" is not imported at t/author-pod-spell.t line 17.

Where are you seeing this? The distribution builds fine at master HEAD, and
2.006004 on cpan also looks fine

> bisect shows this was caused by this patch. I need to get this fixed, and a test added that would catch this regression. I thought my test suite did have tests to catch this, maybe something about the stage change... but I thought `Bootstrap::lib` would make the generated test the same as the final test. I'm looking into it, but if I can't find a fix in a couple of hours I have to revert this to avoid breaking someone elses code.

The test there isn't getting munged before it is being renamed to another
location by ExtraTests, before the original plugin can find it by name and
change the template into real code.

That's why I removed ExtraTests from @Basic and re-added it in at the
bottom of dist.ini.
